module.exports = {
  removeComments: true,
  // removeCommentsFromCDATA: false,
  // removeCDATASectionsFromCDATA: false,
  collapseWhitespace: true,
  // conservativeCollapse: false,
  // collapseInlineTagWhitespace: false,
  // preserveLineBreaks: false,
  // collapseBooleanAttributes: true,
  removeTagWhitespace: true,
  // removeAttributeQuotes: false,
  removeRedundantAttributes: true,
  // preventAttributesEscaping: false,
  // useShortDoctype: false,
  // removeEmptyAttributes: false,
  // removeScriptTypeAttributes: false,
  // removeStyleLinkTypeAttributes: false,
  // removeOptionalTags: false,
  // removeEmptyElements: false,
  // lint: false,
  // keepClosingSlash: false,
  // caseSensitive: false,
  minifyJS: true,
  minifyCSS: true,
  minifyURLs: true,
  // ignoreCustomComments: false,
  // ignoreCustomFragments: false,
  // processScripts: false,
  // maxLineLength: false,
  // customEventAttributes: false,
  // customAttrAssign: false,
  // customAttrSurround: false,
  // customAttrCollapse: false,
  quoteCharacter: "\""
}
